<?php
/**
 * @package LearnDash Course Grid
 * @version 1.4.1
 */
/*
Plugin Name: LearnDash Course Grid
Plugin URI: http://www.learndash.com
Description: LearnDash Course Grid
Version: 1.4.1
Author: LearnDash
Author URI: http://www.learndash.com
Text Domain: learndash_course_grid
*/

define( 'LEARNDASH_COURSE_GRID_FILE', __FILE__ );

add_action("plugins_loaded", "learndash_course_grid_localize");
function learndash_course_grid_localize() {
	$locale = apply_filters( 'plugin_locale', get_locale(), 'learndash_course_grid' );
	load_textdomain( 'learndash_course_grid', WP_LANG_DIR . '/learndash_course_grid/learndash_course_grid-' . $locale . '.mo' );
	load_plugin_textdomain( 'learndash_course_grid', false, dirname( plugin_basename( __FILE__ ) ) . '/languages/' );                
}

//add_action( 'wp_enqueue_scripts', 'learndash_course_grid_css_head', 0);
//function learndash_course_grid_css_head() {
//	wp_enqueue_style( 'ld-cga-bootstrap', plugins_url( 'bootstrap.min.css', __FILE__ ) );
//}
add_action( 'admin_enqueue_scripts', 'learndash_course_grid_admin', 0);
function learndash_course_grid_admin() {
	global $pagenow, $post;

	if($pagenow == "post.php" && $post->post_type == "sfwd-courses" || $pagenow == "post-new.php" && @$_GET["post_type"] == "sfwd-courses")
	wp_enqueue_script( 'learndash_course_grid_js', plugins_url( 'script.js', __FILE__ ), array('jquery') );
}
add_filter("the_content", "learndash_course_grid_css");
function learndash_course_grid_css( $content ) {
	if ( 
		   strpos( $content, "[ld_course_list" ) === false
		&& strpos( $content, "[ld_lesson_list" ) === false
		&& strpos( $content, "[ld_quiz_list" )   === false
		&& strpos( $content, "[ld_topic_list" )  === false
	) {
		return $content;
	}

	wp_enqueue_style( 'learndash_course_grid_css', plugins_url( 'style.css', __FILE__ ) );
	wp_enqueue_script( 'learndash_course_grid_js', plugins_url( 'script.js', __FILE__ ), array('jquery' ) );
	wp_enqueue_style( 'ld-cga-bootstrap', plugins_url( 'bootstrap.min.css', __FILE__ ) );
	
	return preg_replace( '/(.*\[ld_\w+_list.*)/', '<div id="ld_course_list">$1</div>', $content );
}

add_filter( 'learndash_template', 'learndash_course_grid_course_list', 99, 5);
function learndash_course_grid_course_list($filepath, $name, $args, $echo, $return_file_path) {
	if ( $name == "course_list_template" && $filepath == LEARNDASH_LMS_PLUGIN_DIR . 'templates/course_list_template.php' ) {
		return dirname(__FILE__)."/course_list_template.php";
	}

	return $filepath;
}

function learndash_course_grid_course_list_ending($output) {
	return $output."<br style='clear:both'>";
}
add_filter("ld_course_list", "learndash_course_grid_course_list_ending",1, 1);


add_filter("learndash_post_args", "learndash_course_grid_post_args", 10, 1);

function learndash_course_grid_post_args($post_args) {
	foreach($post_args as $key => $post_arg) {
		if($post_arg["post_type"] == "sfwd-courses") {
			$course_short_description = array(
                                              'name' => __('Course Short Description', 'learndash_course_grid'),
                                              'type' => 'textarea',
                                              'help_text' => __('A short description of the course to show on course list generated by course list shortcode.', 'learndash_course_grid'),
                                            );
			$post_args[$key]["fields"] = array("course_short_description" => $course_short_description) + $post_args[$key]["fields"];
		}
	}
	return $post_args;
}

add_action( 'add_meta_boxes', 'learndash_course_grid_add_meta_box' );
/**
 * Add course grid settings meta box
 */
function learndash_course_grid_add_meta_box()
{	
	add_meta_box( 'learndash-course-grid-meta-box', __( 'Course Grid Settings', 'learndash_course_grid' ), 'learndash_course_grid_output_meta_box', array( 'sfwd-courses', 'sfwd-lessons', 'sfwd-topic', 'sfwd-quiz' ), 'advanced', 'low', array() );
}

/**
 * Output course grid settings meta box
 * 
 * @param  array $args List or args passed on callback function
 */
function learndash_course_grid_output_meta_box( $args )
{
	$post_id       = get_the_ID();
	$enable_video  = get_post_meta( $post_id, '_learndash_course_grid_enable_video_preview', true );
	$embed_code    = get_post_meta( $post_id, '_learndash_course_grid_video_embed_code', true );
	$button_text   = get_post_meta( $post_id, '_learndash_course_grid_custom_button_text', true );

	$video_html = <<<EOD
<video controls>
	<source src="video-file.mp4" type="video/mp4">
</video>
EOD;
	?>

	<?php wp_nonce_field( 'learndash_course_grid_save', 'learndash_course_grid_nonce' ); ?>
	<script type="text/javascript">
		jQuery(document).ready(function($) {
			$( window ).load( function() {
				if ( $( 'input[name="learndash_course_grid_enable_video_preview"]' ).is( ':checked' ) ) {
					$( '#learndash_course_grid_video_embed_code_field' ).show();
				}
			} );

			$( 'input[name="learndash_course_grid_enable_video_preview"]' ).change( function( e ) {
				if ( $( this ).prop( 'checked' ) ) {
					$( '#learndash_course_grid_video_embed_code_field' ).show();
				} else {
					$( '#learndash_course_grid_video_embed_code_field' ).hide();
				}
			});
		});
	</script>
	<div class="sfwd sfwd_options">
		<div class="sfwd_input">
			<span class="sfwd_option_label" style="text-align:right;vertical-align:top;">
				<a class="sfwd_help_text_link" style="cursor:pointer;" title="Click for Help!" onclick="toggleVisibility('learndash_course_grid_enable_video_preview');"><img src="<?php echo LEARNDASH_LMS_PLUGIN_URL . 'assets/images/question.png' ?>">
				<label class="sfwd_label textinput"><?php _e( 'Enable Video Preview' ); ?></label></a>
			</span>
			<span class="sfwd_option_input">
				<div class="sfwd_option_div">
					<input type="hidden" name="learndash_course_grid_enable_video_preview" value="0">
					<input type="checkbox" name="learndash_course_grid_enable_video_preview" value="1" <?php checked( $enable_video, 1, true ); ?>>
				</div>
				<div class="sfwd_help_text_div" style="display:none" id="learndash_course_grid_enable_video_preview">
					<label class="sfwd_help_text"><?php _e( 'Select this option to use a featured video for this course in the course grid. If not selected, the featured image will be used.' ); ?></label>
				</div>
			</span>
			<p style="clear:left"></p>
		</div>
		<div class="sfwd_input" style="display: none;" id="learndash_course_grid_video_embed_code_field">
			<span class="sfwd_option_label" style="text-align:right;vertical-align:top;">
				<a class="sfwd_help_text_link" style="cursor:pointer;" title="Click for Help!" onclick="toggleVisibility('learndash_course_grid_video_embed_code');"><img src="<?php echo LEARNDASH_LMS_PLUGIN_URL . 'assets/images/question.png' ?>">
				<label class="sfwd_label textinput"><?php _e( 'Video URL or Embed Code' ); ?></label></a>
			</span>
			<span class="sfwd_option_input">
				<div class="sfwd_option_div">
					<textarea name="learndash_course_grid_video_embed_code" rows="2" cols="57"><?php echo esc_textarea( $embed_code ); ?></textarea>
				</div>
				<div class="sfwd_help_text_div" style="display:none" id="learndash_course_grid_video_embed_code">
					<label class="sfwd_help_text"><?php _e( 'Paste the direct video URL (or embed code) of the video you want to use in the course grid. If you have a video file URL, then you can use the video tag to embed your video like this:' ); ?> <code><?php echo esc_html( $video_html ); ?></code>
					</label>
				</div>
			</span>
			<p style="clear:left"></p>
		</div>
		<div class="sfwd_input" id="learndash_course_grid_custom_button_text_field">
			<span class="sfwd_option_label" style="text-align:right;vertical-align:top;">
				<a class="sfwd_help_text_link" style="cursor:pointer;" title="Click for Help!" onclick="toggleVisibility('learndash_course_grid_custom_button_text');"><img src="<?php echo LEARNDASH_LMS_PLUGIN_URL . 'assets/images/question.png' ?>">
				<label class="sfwd_label textinput"><?php _e( 'Custom Button Text', 'learndash_course_grid' ); ?></label></a>
			</span>
			<span class="sfwd_option_input">
				<div class="sfwd_option_div">
					<input name="learndash_course_grid_custom_button_text" type="text" value="<?php echo esc_attr( $button_text ); ?>"></textarea>
				</div>
				<div class="sfwd_help_text_div" style="display:none" id="learndash_course_grid_custom_button_text">
					<label class="sfwd_help_text"><?php _e( 'Use this field to change the default "See More..." button text in the course grid.', 'learndash_course_grid' ); ?>
					</label>
				</div>
			</span>
			<p style="clear:left"></p>
		</div>
	</div>

	<?php
}

add_action( 'save_post', 'learndash_course_grid_save_meta_box', 10, 3 );
/**
 * Save course grid meta box fields
 * 
 * @param  int    $post_id Post ID
 * @param  object $post    WP post object
 * @param  bool   $update  True if post is an update
 */
function learndash_course_grid_save_meta_box( $post_id, $post, $update )
{
	if ( $post->post_type != 'sfwd-courses' ) {
		return;
	}

	if ( wp_is_post_revision( $post_id ) ) {
		return;
	}

	if ( ! isset( $_POST['learndash_course_grid_nonce'] ) ) {
		return;
	}

	if ( ! wp_verify_nonce( $_POST['learndash_course_grid_nonce'], 'learndash_course_grid_save' ) ) {
		wp_die( __( 'Cheatin\' huh?' ) );
	}

	$allowed_html = wp_kses_allowed_html( 'learndash_course_grid_meta_box' );

	update_post_meta( $post_id, '_learndash_course_grid_enable_video_preview', wp_filter_kses( $_POST['learndash_course_grid_enable_video_preview'] ) );

	update_post_meta( $post_id, '_learndash_course_grid_video_embed_code', wp_kses( $_POST['learndash_course_grid_video_embed_code'], $allowed_html ) );

	update_post_meta( $post_id, '_learndash_course_grid_custom_button_text', sanitize_text_field( trim( $_POST['learndash_course_grid_custom_button_text'] ) ) );
}

add_filter( 'wp_kses_allowed_html', 'learndash_course_grid_allowed_html', 10, 2 );
/**
 * Filter to allow HTML tags for course grid meta box settings
 * 
 * @param  array  $tags    List of HTML tags
 * @param  string $context String of context
 * @return array           New allowed HTML tags
 */
function learndash_course_grid_allowed_html( $tags, $context )
{
	if ( 'learndash_course_grid_meta_box' == $context ) {
		$tags['iframe'] = array(
			'allowfullscreen' => true,
			'frameborder' => true,
			'height' => true,
			'src' => true,
			'width' => true,
		);

		$tags['video'] = array(
			'controls' => true,
			'autoplay' => true,
			'height' => true,
			'width' => true,
			'src' => true,
		);

		$tags['source'] = array(
			'src' => true,
			'media' => true,
			'sizes' => true,
			'type' => true,
		);

		$tags['track'] = array(
			'default' => true,
			'src' => true,
			'srclang' => true,
			'kind' => true,
			'label' => true,
		);
	}

	return $tags;
}